#!/usr/bin/env node

/**
 * Fetch DoD Issuances (DoDI) from the WHS Directives Division
 *
 * Scrapes the DoDI issuances table and generates a static JavaScript data
 * file for the application, so the DODI tab renders with no network call.
 *
 * Source: https://www.esd.whs.mil/Directives/issuances/dodi/
 * Target: lib/dodi-data.js
 *
 * WHY STATIC. Until 15 Sep 2026 the app fetched this page in the browser and
 * fell back to the Render proxy. Both paths are dead for every user: the site
 * sends no Access-Control-Allow-Origin header, and the proxy's domain
 * allowlist does not include esd.whs.mil. The site also sits behind Akamai and
 * answers 403 to datacenter ranges (cloud containers, GitHub Actions runners),
 * so even an allowlisted proxy on Render is not a safe bet. Same situation as
 * sja.marines.mil, same answer: fetch from a workstation, commit the result.
 *
 *   npm run fetch-dodi
 *
 * Like scripts/fetch-court-martial.mjs, this script never writes an empty or
 * sharply smaller file. A failed scrape leaves the committed data in place and
 * exits non-zero.
 */

import { readFile, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const SOURCE_URL = 'https://www.esd.whs.mil/Directives/issuances/dodi/';
const OUTPUT_FILE = join(__dirname, '../lib/dodi-data.js');
const SHRINK_TOLERANCE = 0.8;

const BROWSER_HEADERS = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
  'Accept-Language': 'en-US,en;q=0.9',
  'Upgrade-Insecure-Requests': '1',
  'Sec-Fetch-Dest': 'document',
  'Sec-Fetch-Mode': 'navigate',
  'Sec-Fetch-Site': 'none'
};

async function fetchPage(url) {
  const response = await fetch(url, { headers: BROWSER_HEADERS });
  if (!response.ok) {
    throw new Error(`HTTP ${response.status} for ${url}`);
  }
  return response.text();
}

const clean = text => (text || '').replace(/\s+/g, ' ').trim();

/**
 * Parse the DNN UserDefinedTable that drives the issuances page. Ported from
 * parseDodiTable in app.js (the browser version, validated against the live
 * DOM before the type went static). Each issuance row carries class
 * dnnGridItem or dnnGridAltItem. Cells in order: Issuance #, Issuance Date,
 * Subject, CH #, CH Date, Related Memo, OPR.
 */
export function parseDodi($, baseUrl = SOURCE_URL) {
  const items = [];
  $('tr.dnnGridItem, tr.dnnGridAltItem').each((_, tr) => {
    const cells = $(tr).children('td');
    if (cells.length < 7) { return; }

    const first = cells.eq(0);
    const anchor = first.find('a[href]').first();
    const id = clean(anchor.length ? anchor.text() : first.text());
    if (!id) { return; }

    let link = clean(anchor.attr('href'));
    if (link) {
      try { link = new URL(link, baseUrl).href; } catch { /* keep raw */ }
    }

    items.push({
      id,
      link,
      issuanceDate: clean(cells.eq(1).text()),
      subject: clean(cells.eq(2).text()),
      chNumber: clean(cells.eq(3).text()),
      chDate: clean(cells.eq(4).text()),
      relatedMemo: clean(cells.eq(5).text()),
      opr: clean(cells.eq(6).text())
    });
  });
  return items;
}

async function existingRecordCount() {
  try {
    const current = await readFile(OUTPUT_FILE, 'utf-8');
    const match = current.match(/totalRecords:\s*(\d+)/);
    return match ? Number(match[1]) : 0;
  } catch {
    return 0;
  }
}

export function renderDataFile(issuances, now = new Date().toISOString()) {
  return `/**
 * DoD Issuances (DoDI) Data
 *
 * Auto-generated from the WHS Directives Division issuances table
 * Source: ${SOURCE_URL}
 * Generated: ${now}
 * Total Records: ${issuances.length}
 *
 * This file is automatically generated by scripts/fetch-dodi.mjs
 * DO NOT EDIT MANUALLY
 */

// DoD Issuance data structure
const DODI_ISSUANCES = ${JSON.stringify(issuances, null, 2)};

const DODI_META = {
  sourceUrl: '${SOURCE_URL}',
  generatedAt: '${now}',
  totalRecords: ${issuances.length},
  lastUpdate: '${now}'
};

// Export for use in application
if (typeof window !== 'undefined') {
  window.DODI_ISSUANCES = DODI_ISSUANCES;
  window.DODI_META = DODI_META;
}

// Also support module exports for testing
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    DODI_ISSUANCES,
    DODI_META
  };
}
`;
}

async function main() {
  console.log('[DoDI] Starting fetch process...');
  const cheerio = await import('cheerio');

  let issuances;
  try {
    console.log('[DoDI] Fetching:', SOURCE_URL);
    const html = await fetchPage(SOURCE_URL);
    issuances = parseDodi(cheerio.load(html));
    console.log(`[DoDI] Parsed ${issuances.length} rows from the DNN table`);
  } catch (error) {
    console.error('[DoDI] Fetch failed:', error.message);
    console.error('[DoDI] Existing data left untouched. Run this from a workstation, not CI or a cloud container.');
    process.exit(1);
  }

  const previous = await existingRecordCount();

  if (issuances.length === 0) {
    console.error('[DoDI] Parsed zero issuances. Existing data left untouched.');
    console.error('[DoDI] The table markup likely changed. Check parseDodi against the live page.');
    process.exit(1);
  }

  if (previous > 0 && issuances.length < previous * SHRINK_TOLERANCE) {
    console.error(`[DoDI] Parsed ${issuances.length} issuances against ${previous} committed.`);
    console.error('[DoDI] That drop looks like a partial scrape. Existing data left untouched.');
    console.error('[DoDI] Re-run, and if the listing genuinely shrank, delete the data file first.');
    process.exit(1);
  }

  await writeFile(OUTPUT_FILE, renderDataFile(issuances), 'utf-8');
  console.log(`[DoDI] Data file written to: ${OUTPUT_FILE}`);
  console.log(`[DoDI] Total records: ${issuances.length}`);
  console.log('[DoDI] Complete');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
